config/routes.rb
Rails.application.routes.draw do
  delete '/logout' => "sessions#destroy"
  root "flights#index"
  resources :bookings, only: [:new, :edit, :index]
  resources :flights,  only:  :index do
    resources :bookings
  end
  get 'user/bookings' => "bookings#index"
  get "/auth/:provider/callback" => "sessions#create"
  get "reservation" => "bookings#reservation_form"
  post "reservations" => "bookings#make_reservation"
end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :from_flights, class_name: "Flight", foreign_key: :from_airport_id
  has_many :to_flights, class_name: "Flight", foreign_key: :to_airport_id
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight
  belongs_to :user
  has_many :passengers
  validates_associated :passengers
  accepts_nested_attributes_for :passengers, reject_if: :all_blank,
                                             allow_destroy: true
  validates :flight_id, presence: true
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :from_airport, class_name: "Airport"
  belongs_to :to_airport, class_name: "Airport"
  has_many :bookings
  validates :to_airport_id, presence: true
  validates :from_airport_id, presence: true
  class << self
    def date_list
      dates = all.order(date: :asc)
      dates.map do |flight|
        flight.date.strftime("#{flight.date.day.ordinalize} %B %Y")
      end.uniq
    end

    def search(hash)
      hash[:date] = correct_date(hash[:date])
      where(hash)
    end

    def correct_date(date)
      unless date.nil?
        date = date.to_date
        date.beginning_of_day..date.end_of_day
      end
    end
  end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  before_save { self.email = email.downcase }
  belongs_to :booking
  VALID_NAME_REGEX = /\A([a-zA-Z]+(\-|\s)?[a-zA-Z]+)+\z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PHONE_REGEX = /\A(\+)?(\d+(\s|-)?\d+)+\z/
  validates :name, presence: true, format: { with: VALID_NAME_REGEX }
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :phone_number, format: { with: VALID_PHONE_REGEX }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bookings
  VALID_NAME_REGEX = /\A\D+\z/
  validates :name, presence: true, length: { maximum: 50 },
                   format: { with: VALID_NAME_REGEX }
  validates :uid, presence: true
  validates :provider, presence: true
  class << self
    def from_omniauth(auth_hash)
      user = find_or_create_by(uid: auth_hash["uid"],
                               provider: auth_hash["provider"])
      user.name = auth_hash["info"]["name"]
      user.email = auth_hash["info"]["email"]
      user.image_url = auth_hash["info"]["image"]
      user.save!
      user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :ensure_login, only: :index
  def index
    @bookings = current_user.bookings
  end

  def new
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.new
  end

  def show
    @booking = Booking.find_by_id(params[:id])
  end

  def reservation_form
  end

  def make_reservation
    if !Booking.find_by_id(params[:id])
      flash[:danger] = "invalid code, please enter a correct booking number"
      redirect_to :back
    elsif Booking.find(params[:id]).user_id
      flash[:danger] = "This booking may not belong to you"
      redirect_to :back
    else
      redirect_to edit_booking_path(params[:id])
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
    render :new
  end

  def create
    @flight = Flight.find(params[:flight_id])
    if params[:booking].nil?
      flash[:notice] = "Please add at least one passenger"
      redirect_to :back
    else
      set_price
    end
  end

  def update
    @booking = Booking.find(params[:id])
    a = params[:booking][:passengers_attributes].values
    passenger_integrity(a)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    flash[:notice] = "You have just deleted a booking"
    redirect_to flight_bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(passengers_attributes: [:id, :name, :email,
                                                            :phone_number,
                                                            :_destroy])
  end

  def set_price
    @booking = @flight.bookings.new(booking_params)
    @booking.price = booking_params[:passengers_attributes].keys.count * 1200
    save
  end

  def save
    @booking.user_id = current_user.id if current_user
    if @booking.save
      flash[:notice] = "This flight has been booked successfully"
      thanks_mail
    else
      @flight = @booking.flight
      render :new
    end
  end

  def passenger_integrity(a)
    if a.all? { |i| i.values[3] != "false" }
      flash[:notice] = "Please add at least one passenger"
      redirect_to :back
    else
      @booking.update(booking_params)
      price_update
    end
  end

  def thanks_mail
    @booking.passengers.each do |passenger|
      UserMailer.thanks(passenger).deliver_now
    end
    redirect_to flight_booking_path(@booking.flight, @booking)
  end

  def price_update
    @booking.price = @booking.passengers.count * 1200
    if @booking.save
      flash[:notice] = "This flight has been updated successfully"
      mail_update
    else
      @flight = @booking.flight
      render :new
    end
  end

  def mail_update
    @booking.passengers.each do |passenger|
      UserMailer.updated(passenger).deliver_now
    end
    redirect_to flight_booking_path(@booking.flight, @booking)
  end

  def ensure_login
    unless current_user
      flash[:notice] = "Please log in first"
      redirect_to root_path
    end
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :same_airport, only: :index
  def index
    @airports = Airport.all.map do |airport|
      [(airport.name + ", " + airport.city), airport.id]
    end
    set_variables
  end

  private

  def set_variables
    @dates = Flight.date_list
    @hash = params.permit(:from_airport_id, :to_airport_id, :date)
    @flights = Flight.search(@hash)
  end

  def same_airport
    if params[:commit] == "Search"
      if params[:from_airport_id] == params[:to_airport_id]
        flash[:danger] = "Your Departure and Destination "\
        "Airports Can Not Be the Same"
        redirect_to :back
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    begin
      @user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}!"
    rescue
      flash[:warning] = "There was an error while trying to authenticate you..."
    end
    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = "You have logged out successfully"
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/bookings/_passenger_fields.html.erb
  <div class="row nested-fields">
    <div class="col-md-12 passenger-box">
      <h3>Passenger</h3>

      <div class="form-group">
        <%= f.label :name, "Name:", class: "control-label col-sm-2" %>
        <div class="col-md-9">
          <%= f.text_field :name, class: "form-control", placeholder: "Tell us your name", required: true%>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :email, "Email:", class: "control-label col-sm-2" %>
        <div class="col-md-9">
          <%= f.email_field :email, class: "form-control", placeholder: "Email Address", required: true %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :phone_number, "Phone", class: "control-label col-sm-2" %>
        <div class="col-md-9">
          <%= f.phone_field :phone_number, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= link_to_remove_association "Remove Passenger", f %>
      </div>
    </div>
  </div>

app/views/bookings/index.html.erb
<% if @bookings.count == 0 %>
  <h1 class="text-danger">You have no previous bookings<br>Try and make a <%= link_to "new booking", root_path %></h1>
<% else %>
  <h1 class= "text-danger">
      You have made <%= pluralize(@bookings.count, "booking") %>...
  </h1>
  <div class="center jumbotron">
      <% @bookings.each do |booking| %>
       <h4> <span class= "text-warning">Booking Number: </span><strong>00<%= booking.id %></strong></h4>
       <h4> <span class= "text-warning">Departure Airport: </span><strong><%= booking.flight.from_airport.name + ", " + booking.flight.from_airport.city %></strong></h4>
       <h4> <span class= "text-warning">Destination Airport: </span><strong><%= booking.flight.to_airport.name + ", " + booking.flight.to_airport.city %></strong></h4>
       <h4> <span class= "text-warning">Departure Date: </span><strong><%= booking.flight.date.strftime("%d/%m/%Y") %></strong></h4>
       <h4> <span class= "text-warning">Take-off Time: </span><strong><%= booking.flight.time %></strong></h4>
       <h4> <span class= "text-warning">No. of passengers: </span><strong><%= booking.passengers.count %></strong></h4>
       <h4> <span class= "text-warning">Total Price: </span><strong></strong>$ <%= booking.price %></h4>
       <h4> <span class= "text-warning">Time of booking: </span><strong><%= booking.updated_at %></strong></h4>
       <%  if booking.flight.date > Time.now %>
         <h5><%= link_to "Edit", edit_booking_path(booking) %></h5>
         <h5><%= link_to "Delete", flight_booking_path(booking.flight, booking), method: :delete, data: {confirm: "Are you sure you want to delete this booking?"} %></h5>
         <h1>--------------------------------------------------------------------------</h1>
       <% end %>
      <% end %>
    </div>
    <% end %>
    <h4><%= link_to root_path do %>
      <i class="fa fa-home"></i> Go Home
      <% end %>
    </h4>

app/views/bookings/new.html.erb
<div class="row passenger_details">
    <div class="col-md-6 col-md-offset-3">
    <% unless current_user %>
      <h5>Please, know that you might have to login in order to keep track of your bookings</h5>
    <% end %>
      <div class="row">
        <h2>Passenger Details</h2>
        <p>Please enter passenger details for flight:</p>
        <h2>Price per passenger = $ 1,200</h2>
        <div class=" col-md-12 flight-details">
          <div class"panel-body">
            <table class="table">
              <thead>
                <tr>
                  <th>Flight Number:</th>
                  <th>Departure Airport</th>
                  <th>Destination Airport</th>
                  <th>Departure Date</th>
                  <th>Departure Time</th>
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td><%= @flight.id %></td>
                  <td><%= @flight.from_airport.name + ", " + @flight.from_airport.city %></td>
                  <td><%= @flight.to_airport.name + ", " + @flight.to_airport.city %></td>
                  <td><%= @flight.date.strftime("#{@flight.date.day.ordinalize} %B %Y") %></td>
                  <td><%= @flight.time %></td>
                </tr>
              </tbody>
            </table>
            </div>
          </div>
          </div>

      <%= form_for [@flight, @booking], :html => { :class => "form-horizontal" } do |f|  %>
        <% if @booking.errors.any? %>
          <div id="error_explanation">

            <h2>
              <%= pluralize(@booking.errors.count, "error") %>
            </h2>

            <ul>
              <% @booking.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div id="passenger">
          <%= f.fields_for :passengers do |passenger| %>
          <%= render "passenger_fields", f: passenger %>
          <% end %>
        </div>
        <div class="links">
          <%= link_to_add_association 'Add Passenger', f, :passengers %>
        </div>
        <%= f.submit "Book Flight", class: "btn btn-success btn-lg col-md-4 col-md-offset-4" %>
    <% end %>
  </div>
</div>

app/views/bookings/reservation_form.html.erb
  <div class="center jumbotron">
      <%= form_tag(reservations_path, method: :post, class: "col l9 offset-l1 s12 left") do %>
        <%= label_tag :id, "Enter Booking Confirmation Code" %>
        <%= text_field_tag :id %><p>                   </p>
       <%= submit_tag "Find Reservation", class: "btn btn-primary" %>
      <% end %>
  </div>
  <!--class: "form-control", placeholder: "type here", required: true, pattern: /d+/-->

app/views/bookings/show.html.erb
<h1>Your Flight has Been Booked!<br>
Here are your flight details below</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3 booking" style="background-color: #BFD2EA">

    <h1>Flight Details</h3>
    <h3> <span class= "text-warning">Total Price: </span><strong>$ <%= @booking.price %></strong></h4>

    <h3>  <span class= "text-warning">Booking Number: </span><strong>00<%= @booking.id %> </strong></h3>
    <h3>  <span class= "text-warning">Departure Airport: </span><strong> <%= "#{@booking.flight.from_airport.name}, #{@booking.flight.from_airport.city}" %></strong></h3>
    <h3>  <span class= "text-warning">Destination Airport: </span><strong> <%= "#{@booking.flight.to_airport.name}, #{@booking.flight.to_airport.city}" %></strong></h3>
    <h3>  <span class= "text-warning">Departure Date: </span><strong> <%= @booking.flight.date.strftime("#{@booking.flight.date.day.ordinalize} %B %Y") %></strong></h3>
    <h3>  <span class= "text-warning">Departure Time: </span><strong> <%= @booking.flight.time %> </strong></h3>
    <h3>  <span class= "text-warning">Duration: </span><strong> <%= @booking.flight.duration %> hours </strong></h3>

    <h3>Passenger details</h3>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone number</th>
        </tr>
      </thead>

      <tbody>
        <% @booking.passengers.each do |passenger| %>
          <tr>
            <td><%= passenger.name %></td>
            <td><%= passenger.email %></td>
            <td><%= passenger.phone_number %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h3>You will receive a confirmation email soon enough</h3>

    <div class="row">
      <div class="col-sm-4">
        <h4>It is now safe to close this window or you may decide<br>
          to make another booking <%= link_to "Here", root_path %>.</h4>
      </div>

      <div class="col-sm-6 offset-s2 pull-right bookings-btn-container">
        <%= link_to "Go to your bookings list", user_bookings_path, class: "btn btn-primary bookings-btn" %>
      </div>
    </div>
  </div>
</div>

app/views/flights/index.html.erb
<% unless current_user %>
  <div class= "center reservation">
    <%= link_to "Make Reservation", "reservation", class: "btn btn-primary" %>
  </div>
<% end %>
<div class="row search">

  <div class="col-sm-10 col-sm-offset-1">
    <h3 class="mid">Search for a flight</h3>
    </div>

    <div class="col-sm-10 col-sm-offset-2">

      <%= form_tag(flights_path, method: "get") do %>


        <div class="form-group col-md-3">
          <%= label_tag(:from_airport_id, "Departure Airport:") %>
          <%= select_tag(:from_airport_id, options_for_select(@airports, @hash[:from_airport_id]), class: "form-control") %>
        </div>

        <div class="form-group col-md-3">
          <%= label_tag(:to_airport_id, "Destination Airport:") %>
          <%= select_tag(:to_airport_id, options_for_select(@airports, @hash[:to_airport_id]), class: "form-control", id: "destination-select") %>
        </div>

        <div class="form-group col-md-3">
          <%= label_tag(:date, "Date:") %>
          <%= select_tag(:date, options_for_select(@dates, @hash[:date]), class: "form-control") %>
        </div>
      <% if current_user %>
        <%= submit_tag "Search", class: "btn btn-primary col-md-3 col-md-offset-1 below" %>
        <%= link_to "Manage/View Past bookings", 'user/bookings', class: "btn btn-primary col-md-3 col-md-offset-1 below" %>
      <% else %>
      <%= submit_tag "Search", class: "btn btn-primary col-md-3 col-md-offset-3 below" %>
      <% end %>
      <% end %>




      </div>
  </div>
</div>
<% unless @flights.empty? %>
  <div class="row search-results">

    <div class="col-sm-6 col-sm-offset-3   ">
      <h3>Choose a flight</h3>

      <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Flight No:</th>
            <th>Departing From:</th>
            <th>Destination</th>
            <th>Date:</th>
            <th>Time:</th>
          </tr>
        </thead>

        <%= form_tag(new_booking_path, method: "get") do %>
          <tbody>
            <% @flights.each do |flight| %>
              <tr>
                <td><%= radio_button_tag(:flight_id, flight.id, class: "flight_select")  %></td>
                <td><%= flight.id %></td>
                <td><%= flight.from_airport.city %></td>
                <td><%= flight.to_airport.city %></td>
                <td><%= flight.date.strftime("#{flight.date.day.ordinalize} %B %Y") %></td>
                <td><%= flight.time %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
      </div>
      <div class= "continue">
          <%= submit_tag "Continue", class: "btn btn-success col-md-4 col-md-offset-8" %>
      </div>
        <% end %>

    </div>
  </div>
<% end %>
<% if @flights.empty? && @hash[:date] && @hash[:from_airport_id] != @hash[:to_airport_id] %>
  <h3>We are sorry, but there are no flights traveling<br>
    from <%= Airport.find(@hash[:from_airport_id]).city %>
    to <%= Airport.find(@hash[:to_airport_id]).city %> on this day<br>
    Try a different day
  </h3>
<% end %>
<% @flights = [] %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-fluid">
    <div class="col-sm-2">
      <div class="contact">
        <h4> Contact me:</h4>
          <ul>
            <li><%= link_to '<i class="fa fa-twitter-square"></i>'.html_safe, "https://twitter.com/Van_Paitin" %></li>
            <li><%= link_to '<i class="fa fa-github-square"></i>'.html_safe, "https://github.com/andela-mpitan" %></li>
          </ul>
      </div>
    </div>

      <div class="col-sm-4 col-sm-offset-3">
        <p class="copy">Fly_me &copy; April 2016</p>
      </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
  <i class="fa fa-plane fa-5x link-btn"></i>
    <%= link_to "Fly_me", root_url, class: "navbar-brand logo" %>
    <% if current_user %>
      <ul class="nav navbar-nav pull-right img-caption">
        <li class="link-btn" style="margin-right:10px;"><%= current_user.name %> </li>
        <li><%= image_tag current_user.image_url, alt: current_user.name, class: "img-circle" %></li>
        <li><%= link_to "<span class='link-btn'>Log Out</span>".html_safe, '/logout', method: :delete %></li>
      </ul>
    <% else %>
        <ul class="nav navbar-nav pull-right link-btn">
        <h5>You may sign in with any of the following</h5>
          <li><%= link_to '<i class="fa fa-twitter-square link-btn"></i><br><span class="link-btn">Twitter</span>'.html_safe, '/auth/twitter' %></li>
          <li><%= link_to '<i class="fa fa-facebook-square link-btn"></i><br><span class="link-btn">Facebook</span>'.html_safe, '/auth/facebook' %></li>
          <li><%= link_to '<i class="fa fa-google link-btn"></i><br><span class="link-btn">Google</span>'.html_safe, '/auth/google_oauth2' %></li>
        </ul>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlyMe</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type%> alert-dismissible" role="alert" id="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <ul>
        <li>
          <%= message %>
        </li>
      </ul>
      </div>
    <% end %>
    <%= yield %>

  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/users/show.html.erb
<% if current_user.bookings.count == 0 %>
  <h1>You have no previous bookings<br>Try and make a <%= link_to "new booking", root_path %></h1>
<% else %>
  <h2>
      You have made <%= pluralize(current_user.bookings.count, "booking") %>...
  </h2>
      <table class="table">
        <thead>
          <tr>
            <th>Booking Number:</th>
            <th>Departure Airport</th>
            <th>Destination Airport</th>
            <th>Departure Date</th>
            <th>Take-off Time</th>
            <th>No. of passengers</th>
            <th>Total Price</th>
          </tr>
        </thead>
        <tbody>
        <% current_user.bookings.each do |booking| %>
          <tr>
            <td>00<%= booking.id %></td>
            <td><%= booking.flight.from_airport %></td>
            <td><%= booking.flight.to_airport %></td>
            <td><%= booking.flight.date %></td>
            <td><%= booking.flight.time %></td>
            <td><%= booking.passengers.count %></td>
            <td><%= booking.price %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>
    <h3><%= link_to "Return Home", root_path %></h3>